# https://taskfile.dev

version: '3'

vars:
  REPOSITORY: mouselightdatabrowser
  IMAGE: public-proxy
  REPOIMAGE: "{{.REPOSITORY}}/{{.IMAGE}}"
  MAJOR: 1
  MINOR: 7
  REVISION: 2
  IMAGEWITHVERSION: "{{.REPOIMAGE}}:{{.MAJOR}}"
  IMAGEWITHMINORVERSION: "{{.IMAGEWITHVERSION}}.{{.MINOR}}"
  IMAGEWITHREVERSION: "{{.IMAGEWITHMINORVERSION}}.{{.REVISION}}"
  IMAGELATEST: "{{.REPOIMAGE}}:latest"

tasks:
  build:
    cmds:
      - docker build --platform linux/amd64 --tag {{.IMAGEWITHVERSION}} .
      - docker tag {{.IMAGEWITHVERSION}} {{.IMAGEWITHMINORVERSION}}
      - docker tag {{.IMAGEWITHMINORVERSION}} {{.IMAGEWITHREVERSION}}
      - docker tag {{.IMAGEWITHREVERSION}} {{.IMAGELATEST}}
  release:
    cmds:
      - task: build
      - docker push {{.IMAGEWITHVERSION}}
      - docker push {{.IMAGEWITHMINORVERSION}}
      - docker push {{.IMAGEWITHREVERSION}}
      - docker push {{.IMAGELATEST}}
